version: '3.8'
services:
  my-products-api:
    image: my-products-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - secrets.env
    depends_on:
      - db
    networks:
      - products-api-network
  db:
    image: postgres:latest
    container_name: products_postgres_db
    env_file:
      - secrets.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - products-api-network
networks:
  products-api-network:
    driver: bridge
volumes:
  postgres_data:
